name: Terraform AWS Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: 'eu-central-1'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debug Working Directory
        run: |
          ls -al
          pwd

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Display Terraform Version
        run: terraform version

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform configuration
        run: terraform validate

      - name: Plan Terraform changes
        run: terraform plan

      - name: Apply Terraform changes
        run: terraform apply -auto-approve

      - name: Clean up Terraform
        run: |
          # Note: This step is for cleanup purposes. It will destroy the infrastructure after deployment.
          # Use it carefully, and consider removing it if you want to keep the infrastructure.
          terraform destroy -auto-approve

